<?php
if (!defined('VALID_ROOT')) {
  exit('');
}
/**
 * Language strings English: Imprint page
 *
 * @author George Lewe <george@lewe.com>
 * @copyright Copyright (c) 2014-2026 by George Lewe
 * @link https://www.lewe.com
 *
 * @package TeamCal Neo
 * @since 4.3.0
 */
$LANG['imprint'] = array(
  array(
    'title' => 'Author',
    'text' => '<p>TeamCal Neo was created by George Lewe (<a href="https://www.lewe.com/">Lewe.com</a>).
      TeamCal Neo also uses free modules by other great people providing those awesome technologies to the public.
      See detailed credits on the <a href="index.php?action=about">About page</a>.</p>',
  ),
  array(
    'title' => 'Content',
    'text' => '<p>All content delivered with the TeamCal Neo application was created by George Lewe (<a href="https://www.lewe.com/">Lewe.com</a>).
      If you feel that any material is used inappropriately, please contact <a href="https://www.lewe.com/contact/">Lewe.com</a>.</p>
      <p>None of the application content, as a whole or in parts may be reproduced, copied or reused in any form or by any means, electronic or mechanical,
      for any purpose, without the express written permission of George Lewe.</p>',
  ),
  array(
    'title' => 'Links',
    'text' => '<p>All links delivered with the TeamCal Neo application are being provided as a convenience
      and for informational purposes only; they do not constitute an endorsement or an approval by TeamCal Neo of the products, services or opinions
      of the corporation or organization or individual. The application provider bears no responsibility for the accuracy, legality or content of the external site or
      for that of subsequent links. Contact the external site for questions regarding its content.</p>',
  ),
  array(
    'title' => 'GDPR',
    'text' => '<p>No personal data is delivered with the TeamCal Neo application. Data privacy protection of any data added by users lies in the
      responsibility of the user.</p><p>TeamCal Neo provides a general GDPR generator. If used, users of the application are obliged to review the generated statement
      and to change or add any details that the generator does not properly cover.</p><p>The application provider bears no responsibility for the accuracy,
      legality or content of the Data Privacy statement used on any installation of the application.</p>',
  ),
  array(
    'title' => 'Google Analytics',
    'text' => '<p>This website may use Google Analytics, if so configured by the administrator, a web analytics service provided by
      Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site.
      The information generated by the cookie about the use of this website will be transmitted to and stored by Google on servers that may reside in the United States.</p>
      <div class="collapse" id="readmore">
         <p>In case IP-anonymization is activated on this website, your IP address will be truncated within the area of Member States of the European Union or
         other parties to the Agreement on the European Economic Area. Only in exceptional cases the whole IP address will be first transferred to a Google server
         in the USA and truncated there. The IP-anonymization is active on this website.</p>
         <p>Google will use this information on behalf of the operator of this website for the purpose of evaluating your use of the website, compiling reports on
         website activity for website operators and providing them other services relating to website activity and internet usage.</p>
         <p>The IP-address, that your Browser conveys within the scope of Google Analytics, will not be associated with any other data held by Google. You may
         refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the
         full functionality of this website. You can also opt-out from being tracked by Google Analytics with effect for the future by downloading and installing
         Google Analytics Opt-out Browser Addon for your current web browser: <a href="https://tools.google.com/dlpage/gaoptout?hl=en">https://tools.google.com/dlpage/gaoptout?hl=en</a>.</p>
         <p>As an alternative to the browser Addon or within browsers on mobile devices, you can <a href="javascript:gaOptout()">click this link</a> in order to
         opt-out from being tracked by Google Analytics within this website in the future (the opt-out applies only for the browser in which you set it and within
         this domain). An opt-out cookie will be stored on your device, which means that you\'ll have to click this link again, if you delete your cookies.</p>
      </div>
      <p><a class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#readmore">Read more/less...</a></p>',
  ),
  array(
    'title' => 'Matomo Analytics',
    'text' => '<p>This website may use Matomo Analytics, if so configured by the administrator, a self hosted analytics service. Matomo tracks statistics about the usage of the website,
      e.g. number of visits, IP address, browser type, operating system, etc. No personal information is stored. To get more details about this contact the administrator of this website.</p>',
  ),
);
