<?php
// AUTO-GENERATED by tools/generate_db_manifest.php - DO NOT EDIT.
// Source: sql/basic.sql
// Generated: 2026-05-23T12:23:06+00:00
//
// Used by the Database Structure repair feature to diff the live
// database against the schema shipped with this release. Table names
// are stored UNPREFIXED; the repair engine applies the installation's
// db_table_prefix at runtime.

return array (
  'generated' => '2026-05-23T12:23:06+00:00',
  'source' => 'sql/basic.sql',
  'prefix' => 'tcneo_',
  'tables' => 
  array (
    'absences' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        2 => 
        array (
          'name' => 'symbol',
          'definition' => 'char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'A\'',
        ),
        3 => 
        array (
          'name' => 'icon',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        4 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        5 => 
        array (
          'name' => 'bgcolor',
          'definition' => 'varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        6 => 
        array (
          'name' => 'bgtrans',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
        7 => 
        array (
          'name' => 'factor',
          'definition' => 'float NOT NULL',
        ),
        8 => 
        array (
          'name' => 'allowance',
          'definition' => 'float NOT NULL',
        ),
        9 => 
        array (
          'name' => 'allowmonth',
          'definition' => 'float NOT NULL',
        ),
        10 => 
        array (
          'name' => 'allowweek',
          'definition' => 'float NOT NULL',
        ),
        11 => 
        array (
          'name' => 'counts_as',
          'definition' => 'int(11) NOT NULL',
        ),
        12 => 
        array (
          'name' => 'show_in_remainder',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        13 => 
        array (
          'name' => 'show_totals',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        14 => 
        array (
          'name' => 'approval_required',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        15 => 
        array (
          'name' => 'counts_as_present',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        16 => 
        array (
          'name' => 'manager_only',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        17 => 
        array (
          'name' => 'hide_in_profile',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        18 => 
        array (
          'name' => 'confidential',
          'definition' => 'tinyint (1) NOT NULL',
        ),
        19 => 
        array (
          'name' => 'takeover',
          'definition' => 'tinyint (1) NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'absence_group' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'absid',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'groupid',
          'definition' => 'int(11) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'absgroup',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'absid',
            1 => 'groupid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_absid',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'absid',
          ),
        ),
        3 => 
        array (
          'name' => 'k_groupid',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'groupid',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'allowances' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        2 => 
        array (
          'name' => 'absid',
          'definition' => 'int(11) NOT NULL',
        ),
        3 => 
        array (
          'name' => 'carryover',
          'definition' => 'smallint(6) DEFAULT 0',
        ),
        4 => 
        array (
          'name' => 'allowance',
          'definition' => 'smallint(6) DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_absid',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'absid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_allowances' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        2 => 
        array (
          'name' => 'absid',
          'definition' => 'int(11) NOT NULL',
        ),
        3 => 
        array (
          'name' => 'carryover',
          'definition' => 'smallint(6) DEFAULT 0',
        ),
        4 => 
        array (
          'name' => 'allowance',
          'definition' => 'smallint(6) DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_absid',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'absid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_daynotes' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'yyyymmdd',
          'definition' => 'varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'all\'',
        ),
        3 => 
        array (
          'name' => 'region',
          'definition' => 'int(11) NOT NULL DEFAULT 1',
        ),
        4 => 
        array (
          'name' => 'daynote',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(16) NOT NULL DEFAULT \'default\'',
        ),
        6 => 
        array (
          'name' => 'confidential',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_yyyymmdd_username_region',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'yyyymmdd',
            1 => 'username',
            2 => 'region',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_templates' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'year',
          'definition' => 'varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'month',
          'definition' => 'char(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'abs1',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'abs2',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        6 => 
        array (
          'name' => 'abs3',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        7 => 
        array (
          'name' => 'abs4',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        8 => 
        array (
          'name' => 'abs5',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        9 => 
        array (
          'name' => 'abs6',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        10 => 
        array (
          'name' => 'abs7',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        11 => 
        array (
          'name' => 'abs8',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        12 => 
        array (
          'name' => 'abs9',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        13 => 
        array (
          'name' => 'abs10',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        14 => 
        array (
          'name' => 'abs11',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        15 => 
        array (
          'name' => 'abs12',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        16 => 
        array (
          'name' => 'abs13',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        17 => 
        array (
          'name' => 'abs14',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        18 => 
        array (
          'name' => 'abs15',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        19 => 
        array (
          'name' => 'abs16',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        20 => 
        array (
          'name' => 'abs17',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        21 => 
        array (
          'name' => 'abs18',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        22 => 
        array (
          'name' => 'abs19',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        23 => 
        array (
          'name' => 'abs20',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        24 => 
        array (
          'name' => 'abs21',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        25 => 
        array (
          'name' => 'abs22',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        26 => 
        array (
          'name' => 'abs23',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        27 => 
        array (
          'name' => 'abs24',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        28 => 
        array (
          'name' => 'abs25',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        29 => 
        array (
          'name' => 'abs26',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        30 => 
        array (
          'name' => 'abs27',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        31 => 
        array (
          'name' => 'abs28',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        32 => 
        array (
          'name' => 'abs29',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        33 => 
        array (
          'name' => 'abs30',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        34 => 
        array (
          'name' => 'abs31',
          'definition' => 'int(11) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_year_month',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'year',
            2 => 'month',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_users' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        1 => 
        array (
          'name' => 'password',
          'definition' => 'varchar(255) DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'firstname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'lastname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'email',
          'definition' => 'varchar(100) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'order_key',
          'definition' => 'varchar(80) NOT NULL DEFAULT \'0\'',
        ),
        6 => 
        array (
          'name' => 'role',
          'definition' => 'int(11) DEFAULT 2',
        ),
        7 => 
        array (
          'name' => 'locked',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        8 => 
        array (
          'name' => 'hidden',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        9 => 
        array (
          'name' => 'onhold',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        10 => 
        array (
          'name' => 'verify',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        11 => 
        array (
          'name' => 'bad_logins',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        12 => 
        array (
          'name' => 'grace_start',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        13 => 
        array (
          'name' => 'last_pw_change',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        14 => 
        array (
          'name' => 'last_login',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        15 => 
        array (
          'name' => 'created',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        1 => 
        array (
          'name' => 'k_firstname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'firstname',
          ),
        ),
        2 => 
        array (
          'name' => 'k_lastname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'lastname',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_user_attachment' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'fileid',
          'definition' => 'int(11) NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_fileid',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'fileid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_user_group' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'groupid',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'type',
          'definition' => 'tinytext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_groupid',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'groupid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        3 => 
        array (
          'name' => 'k_groupid',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'groupid',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_user_message' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'msgid',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'popup',
          'definition' => 'tinyint (4) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        2 => 
        array (
          'name' => 'k_msgid',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'msgid',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'archive_user_option' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'option',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'value',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_option',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'option',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        3 => 
        array (
          'name' => 'k_option',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'option',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'attachments' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'filename',
          'definition' => 'varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'uploader',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_filename',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'filename',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'config' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'value',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_name',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'daynotes' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'yyyymmdd',
          'definition' => 'varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'all\'',
        ),
        3 => 
        array (
          'name' => 'region',
          'definition' => 'int(11) NOT NULL DEFAULT 1',
        ),
        4 => 
        array (
          'name' => 'daynote',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(16) NOT NULL DEFAULT \'default\'',
        ),
        6 => 
        array (
          'name' => 'confidential',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_yyyymmdd_username_region',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'yyyymmdd',
            1 => 'username',
            2 => 'region',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'groups' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'avatar',
          'definition' => 'varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'default_group.png\'',
        ),
        4 => 
        array (
          'name' => 'minpresent',
          'definition' => 'smallint(6) NOT NULL DEFAULT 0',
        ),
        5 => 
        array (
          'name' => 'maxabsent',
          'definition' => 'smallint(6) NOT NULL DEFAULT 9999',
        ),
        6 => 
        array (
          'name' => 'minpresentwe',
          'definition' => 'smallint(6) NOT NULL DEFAULT 0',
        ),
        7 => 
        array (
          'name' => 'maxabsentwe',
          'definition' => 'smallint(6) NOT NULL DEFAULT 9999',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'holidays' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'000000\'',
        ),
        4 => 
        array (
          'name' => 'bgcolor',
          'definition' => 'varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'ffffff\'',
        ),
        5 => 
        array (
          'name' => 'businessday',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
        6 => 
        array (
          'name' => 'noabsence',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
        7 => 
        array (
          'name' => 'keepweekendcolor',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'k_name',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM AUTO_INCREMENT = 6 DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'log' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'type',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'timestamp',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        3 => 
        array (
          'name' => 'ip',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'user',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'event',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'messages' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'timestamp',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        2 => 
        array (
          'name' => 'text',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        3 => 
        array (
          'name' => 'type',
          'definition' => 'varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'k_type',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'type',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'months' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'year',
          'definition' => 'varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'month',
          'definition' => 'char(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'region',
          'definition' => 'int(11) DEFAULT 1',
        ),
        4 => 
        array (
          'name' => 'wday1',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'wday2',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        6 => 
        array (
          'name' => 'wday3',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        7 => 
        array (
          'name' => 'wday4',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        8 => 
        array (
          'name' => 'wday5',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        9 => 
        array (
          'name' => 'wday6',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        10 => 
        array (
          'name' => 'wday7',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        11 => 
        array (
          'name' => 'wday8',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        12 => 
        array (
          'name' => 'wday9',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        13 => 
        array (
          'name' => 'wday10',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        14 => 
        array (
          'name' => 'wday11',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        15 => 
        array (
          'name' => 'wday12',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        16 => 
        array (
          'name' => 'wday13',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        17 => 
        array (
          'name' => 'wday14',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        18 => 
        array (
          'name' => 'wday15',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        19 => 
        array (
          'name' => 'wday16',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        20 => 
        array (
          'name' => 'wday17',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        21 => 
        array (
          'name' => 'wday18',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        22 => 
        array (
          'name' => 'wday19',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        23 => 
        array (
          'name' => 'wday20',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        24 => 
        array (
          'name' => 'wday21',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        25 => 
        array (
          'name' => 'wday22',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        26 => 
        array (
          'name' => 'wday23',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        27 => 
        array (
          'name' => 'wday24',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        28 => 
        array (
          'name' => 'wday25',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        29 => 
        array (
          'name' => 'wday26',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        30 => 
        array (
          'name' => 'wday27',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        31 => 
        array (
          'name' => 'wday28',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        32 => 
        array (
          'name' => 'wday29',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        33 => 
        array (
          'name' => 'wday30',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        34 => 
        array (
          'name' => 'wday31',
          'definition' => 'tinyint (1) DEFAULT NULL',
        ),
        35 => 
        array (
          'name' => 'week1',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        36 => 
        array (
          'name' => 'week2',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        37 => 
        array (
          'name' => 'week3',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        38 => 
        array (
          'name' => 'week4',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        39 => 
        array (
          'name' => 'week5',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        40 => 
        array (
          'name' => 'week6',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        41 => 
        array (
          'name' => 'week7',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        42 => 
        array (
          'name' => 'week8',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        43 => 
        array (
          'name' => 'week9',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        44 => 
        array (
          'name' => 'week10',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        45 => 
        array (
          'name' => 'week11',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        46 => 
        array (
          'name' => 'week12',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        47 => 
        array (
          'name' => 'week13',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        48 => 
        array (
          'name' => 'week14',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        49 => 
        array (
          'name' => 'week15',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        50 => 
        array (
          'name' => 'week16',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        51 => 
        array (
          'name' => 'week17',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        52 => 
        array (
          'name' => 'week18',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        53 => 
        array (
          'name' => 'week19',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        54 => 
        array (
          'name' => 'week20',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        55 => 
        array (
          'name' => 'week21',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        56 => 
        array (
          'name' => 'week22',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        57 => 
        array (
          'name' => 'week23',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        58 => 
        array (
          'name' => 'week24',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        59 => 
        array (
          'name' => 'week25',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        60 => 
        array (
          'name' => 'week26',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        61 => 
        array (
          'name' => 'week27',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        62 => 
        array (
          'name' => 'week28',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        63 => 
        array (
          'name' => 'week29',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        64 => 
        array (
          'name' => 'week30',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        65 => 
        array (
          'name' => 'week31',
          'definition' => 'smallint(6) DEFAULT NULL',
        ),
        66 => 
        array (
          'name' => 'hol1',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        67 => 
        array (
          'name' => 'hol2',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        68 => 
        array (
          'name' => 'hol3',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        69 => 
        array (
          'name' => 'hol4',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        70 => 
        array (
          'name' => 'hol5',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        71 => 
        array (
          'name' => 'hol6',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        72 => 
        array (
          'name' => 'hol7',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        73 => 
        array (
          'name' => 'hol8',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        74 => 
        array (
          'name' => 'hol9',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        75 => 
        array (
          'name' => 'hol10',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        76 => 
        array (
          'name' => 'hol11',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        77 => 
        array (
          'name' => 'hol12',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        78 => 
        array (
          'name' => 'hol13',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        79 => 
        array (
          'name' => 'hol14',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        80 => 
        array (
          'name' => 'hol15',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        81 => 
        array (
          'name' => 'hol16',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        82 => 
        array (
          'name' => 'hol17',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        83 => 
        array (
          'name' => 'hol18',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        84 => 
        array (
          'name' => 'hol19',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        85 => 
        array (
          'name' => 'hol20',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        86 => 
        array (
          'name' => 'hol21',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        87 => 
        array (
          'name' => 'hol22',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        88 => 
        array (
          'name' => 'hol23',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        89 => 
        array (
          'name' => 'hol24',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        90 => 
        array (
          'name' => 'hol25',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        91 => 
        array (
          'name' => 'hol26',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        92 => 
        array (
          'name' => 'hol27',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        93 => 
        array (
          'name' => 'hol28',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        94 => 
        array (
          'name' => 'hol29',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        95 => 
        array (
          'name' => 'hol30',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        96 => 
        array (
          'name' => 'hol31',
          'definition' => 'int(11) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_year_month_region',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'year',
            1 => 'month',
            2 => 'region',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'patterns' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'abs1',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'abs2',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'abs3',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        6 => 
        array (
          'name' => 'abs4',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        7 => 
        array (
          'name' => 'abs5',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        8 => 
        array (
          'name' => 'abs6',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        9 => 
        array (
          'name' => 'abs7',
          'definition' => 'int(11) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'permissions' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'scheme',
          'definition' => 'varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        2 => 
        array (
          'name' => 'permission',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL',
        ),
        3 => 
        array (
          'name' => 'role',
          'definition' => 'int(11) NOT NULL DEFAULT 1',
        ),
        4 => 
        array (
          'name' => 'allowed',
          'definition' => 'tinyint (1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_scheme_permission_role',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'scheme',
            1 => 'permission',
            2 => 'role',
          ),
        ),
        2 => 
        array (
          'name' => 'k_scheme',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'scheme',
          ),
        ),
        3 => 
        array (
          'name' => 'k_permission',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'permission',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'regions' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'k_name',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'region_role' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'regionid',
          'definition' => 'int(11) NOT NULL',
        ),
        2 => 
        array (
          'name' => 'roleid',
          'definition' => 'int(11) NOT NULL',
        ),
        3 => 
        array (
          'name' => 'access',
          'definition' => 'varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT \'edit\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'roles' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'default\'',
        ),
        4 => 
        array (
          'name' => 'created',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp()',
        ),
        5 => 
        array (
          'name' => 'updated',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_name',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM AUTO_INCREMENT = 4 DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'templates' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'year',
          'definition' => 'varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'month',
          'definition' => 'char(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'abs1',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'abs2',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        6 => 
        array (
          'name' => 'abs3',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        7 => 
        array (
          'name' => 'abs4',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        8 => 
        array (
          'name' => 'abs5',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        9 => 
        array (
          'name' => 'abs6',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        10 => 
        array (
          'name' => 'abs7',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        11 => 
        array (
          'name' => 'abs8',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        12 => 
        array (
          'name' => 'abs9',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        13 => 
        array (
          'name' => 'abs10',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        14 => 
        array (
          'name' => 'abs11',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        15 => 
        array (
          'name' => 'abs12',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        16 => 
        array (
          'name' => 'abs13',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        17 => 
        array (
          'name' => 'abs14',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        18 => 
        array (
          'name' => 'abs15',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        19 => 
        array (
          'name' => 'abs16',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        20 => 
        array (
          'name' => 'abs17',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        21 => 
        array (
          'name' => 'abs18',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        22 => 
        array (
          'name' => 'abs19',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        23 => 
        array (
          'name' => 'abs20',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        24 => 
        array (
          'name' => 'abs21',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        25 => 
        array (
          'name' => 'abs22',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        26 => 
        array (
          'name' => 'abs23',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        27 => 
        array (
          'name' => 'abs24',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        28 => 
        array (
          'name' => 'abs25',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        29 => 
        array (
          'name' => 'abs26',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        30 => 
        array (
          'name' => 'abs27',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        31 => 
        array (
          'name' => 'abs28',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        32 => 
        array (
          'name' => 'abs29',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        33 => 
        array (
          'name' => 'abs30',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        34 => 
        array (
          'name' => 'abs31',
          'definition' => 'int(11) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_year_month',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'year',
            2 => 'month',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'users' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        1 => 
        array (
          'name' => 'password',
          'definition' => 'varchar(255) DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'firstname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'lastname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'email',
          'definition' => 'varchar(100) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'order_key',
          'definition' => 'varchar(80) NOT NULL DEFAULT \'0\'',
        ),
        6 => 
        array (
          'name' => 'role',
          'definition' => 'int(11) DEFAULT 2',
        ),
        7 => 
        array (
          'name' => 'locked',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        8 => 
        array (
          'name' => 'hidden',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        9 => 
        array (
          'name' => 'onhold',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        10 => 
        array (
          'name' => 'verify',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        11 => 
        array (
          'name' => 'bad_logins',
          'definition' => 'tinyint (4) DEFAULT 0',
        ),
        12 => 
        array (
          'name' => 'grace_start',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        13 => 
        array (
          'name' => 'last_pw_change',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        14 => 
        array (
          'name' => 'last_login',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
        15 => 
        array (
          'name' => 'created',
          'definition' => 'datetime NOT NULL DEFAULT \'2026-01-01 00:00:00\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        1 => 
        array (
          'name' => 'k_firstname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'firstname',
          ),
        ),
        2 => 
        array (
          'name' => 'k_lastname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'lastname',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'user_attachment' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'fileid',
          'definition' => 'int(11) NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_fileid',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'fileid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'user_group' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'groupid',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'type',
          'definition' => 'tinytext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_groupid',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'groupid',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        3 => 
        array (
          'name' => 'k_groupid',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'groupid',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'user_message' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'msgid',
          'definition' => 'int(11) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'popup',
          'definition' => 'tinyint (4) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        2 => 
        array (
          'name' => 'k_msgid',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'msgid',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
    'user_option' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(11) NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'option',
          'definition' => 'varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'value',
          'definition' => 'text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username_option',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
            1 => 'option',
          ),
        ),
        2 => 
        array (
          'name' => 'k_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        3 => 
        array (
          'name' => 'k_option',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'option',
          ),
        ),
      ),
      'options' => 'ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_bin',
    ),
  ),
  'config' => 
  array (
    'activateMessages' => '1',
    'adminApproval' => '1',
    'alertAutocloseDanger' => '0',
    'alertAutocloseDelay' => '3000',
    'alertAutocloseSuccess' => '1',
    'alertAutocloseWarning' => '0',
    'allowRegistration' => '1',
    'appDescription' => 'A day based online calendar to manage team events',
    'appKeywords' => 'lewe teamcal neo calendar absence event team',
    'appTitle' => 'TeamCal Neo',
    'appURL' => '#',
    'avatarHeight' => '0',
    'avatarMaxSize' => '0',
    'avatarWidth' => '0',
    'badLogins' => '5',
    'calendarFontSize' => '100',
    'cookieConsent' => '1',
    'cookieLifetime' => '80000',
    'currYearRoles' => '3,2',
    'currentYearOnly' => '0',
    'dbURL' => '#',
    'debugHide' => '0',
    'declAbsence' => '0',
    'declAbsenceEnddate' => '',
    'declAbsencePeriod' => 'nowForever',
    'declAbsenceStartdate' => '',
    'declApplyToAll' => '0',
    'declBase' => 'group',
    'declBefore' => '0',
    'declBeforeDate' => '2026-01-01',
    'declBeforeEnddate' => '',
    'declBeforeOption' => 'date',
    'declBeforePeriod' => 'nowForever',
    'declBeforeStartdate' => '',
    'declNotifyAdmin' => '0',
    'declNotifyDirector' => '0',
    'declNotifyManager' => '1',
    'declNotifyUser' => '1',
    'declPeriod1' => '0',
    'declPeriod1End' => '',
    'declPeriod1Enddate' => '',
    'declPeriod1Message' => '',
    'declPeriod1Period' => '',
    'declPeriod1Start' => '',
    'declPeriod1Startdate' => '',
    'declPeriod2' => '0',
    'declPeriod2End' => '',
    'declPeriod2Enddate' => '',
    'declPeriod2Message' => '',
    'declPeriod2Period' => '',
    'declPeriod2Start' => '',
    'declPeriod2Startdate' => '',
    'declPeriod3' => '0',
    'declPeriod3End' => '',
    'declPeriod3Enddate' => '',
    'declPeriod3Message' => '',
    'declPeriod3Period' => '',
    'declPeriod3Start' => '',
    'declPeriod3Startdate' => '',
    'declScope' => '2',
    'declThreshold' => '40',
    'defaultHomepage' => 'home',
    'defaultLanguage' => 'english',
    'defaultMenu' => 'sidebar',
    'defgroupfilter' => 'all',
    'defregion' => 'Default',
    'disableTfa' => '0',
    'emailConfirmation' => '1',
    'emailNoPastNotifications' => '0',
    'emailNotifications' => '0',
    'firstDayOfWeek' => '1',
    'font' => 'default',
    'footerCopyright' => 'Lewe.com',
    'footerCopyrightUrl' => 'http://www.lewe.com',
    'footerSocialLinks' => 'https://www.linkedin.com/in/george-lewe-a9ab6411b',
    'forceTfa' => '0',
    'gdprController' => 'ACME Inc.
123 Street
Hometown, XY 4567
Germany
Email: info@acme.com',
    'gdprFacebook' => '0',
    'gdprGoogleAnalytics' => '0',
    'gdprGooglePlus' => '0',
    'gdprInstagram' => '0',
    'gdprLinkedin' => '1',
    'gdprOfficer' => 'John Doe
Phone: +49 555 12345
Email: john.doe@acme.com',
    'gdprOrganization' => 'ACME Inc.',
    'gdprPaypal' => '0',
    'gdprPinterest' => '0',
    'gdprPolicyPage' => '1',
    'gdprSlideshare' => '0',
    'gdprTumblr' => '0',
    'gdprTwitter' => '0',
    'gdprXing' => '1',
    'gdprYoutube' => '0',
    'googleAnalytics' => '0',
    'googleAnalyticsID' => '',
    'gracePeriod' => '300',
    'hideDaynotes' => '0',
    'hideManagerOnlyAbsences' => '0',
    'hideManagers' => '0',
    'homepage' => 'home',
    'includeRemainder' => '0',
    'includeRemainderTotal' => '0',
    'includeSummary' => '0',
    'includeTotals' => '0',
    'jqtheme' => 'base',
    'licExpiryWarning' => '30',
    'licKey' => '',
    'logCalendar' => '1',
    'logCalendarOptions' => '1',
    'logConfig' => '1',
    'logDatabase' => '1',
    'logDaynote' => '0',
    'logGroup' => '1',
    'logImport' => '1',
    'logLanguage' => 'english',
    'logLog' => '1',
    'logLogin' => '1',
    'logMessage' => '0',
    'logMonth' => '0',
    'logNews' => '1',
    'logPattern' => '1',
    'logPermission' => '1',
    'logRegion' => '1',
    'logRegistration' => '1',
    'logRole' => '1',
    'logUpload' => '1',
    'logUser' => '1',
    'logcolorCalendar' => 'default',
    'logcolorCalendarOptions' => 'danger',
    'logcolorConfig' => 'danger',
    'logcolorDatabase' => 'warning',
    'logcolorDaynote' => 'default',
    'logcolorGroup' => 'primary',
    'logcolorImport' => 'warning',
    'logcolorLog' => 'default',
    'logcolorLogin' => 'success',
    'logcolorMessage' => 'primary',
    'logcolorMonth' => 'default',
    'logcolorPattern' => 'success',
    'logcolorPermission' => 'warning',
    'logcolorRegion' => 'success',
    'logcolorRegistration' => 'success',
    'logcolorRole' => 'primary',
    'logcolorUpload' => 'primary',
    'logcolorUser' => 'primary',
    'logfilterCalendar Options' => '0',
    'logfilterCalendar' => '1',
    'logfilterCalendarOptions' => '1',
    'logfilterConfig' => '1',
    'logfilterDatabase' => '1',
    'logfilterDaynote' => '0',
    'logfilterGroup' => '1',
    'logfilterImport' => '1',
    'logfilterLog' => '1',
    'logfilterLogin' => '1',
    'logfilterMessage' => '0',
    'logfilterMonth' => '0',
    'logfilterNews' => '1',
    'logfilterPattern' => '1',
    'logfilterPermission' => '1',
    'logfilterRegion' => '1',
    'logfilterRegistration' => '1',
    'logfilterRole' => '1',
    'logfilterUpload' => '1',
    'logfilterUser' => '1',
    'logfrom' => '2026-01-01 00:00:00.000000',
    'logperiod' => 'curr_all',
    'logto' => '2026-12-31 23:59:59.999999',
    'mailFrom' => 'TeamCal Neo',
    'mailReply' => 'webmaster@mysite.com',
    'mailSMTP' => '0',
    'mailSMTPAnonymous' => '0',
    'mailSMTPSSL' => '0',
    'mailSMTPhost' => '',
    'mailSMTPpassword' => '',
    'mailSMTPport' => '0',
    'mailSMTPusername' => '',
    'managerOnlyIncludesAdministrator' => '0',
    'markConfidential' => '0',
    'matomoAnalytics' => '0',
    'matomoSiteId' => '',
    'matomoUrl' => '',
    'monitorAbsence' => '0',
    'noCaching' => '1',
    'noIndex' => '0',
    'notificationsAllGroups' => '0',
    'pageHelp' => '1',
    'pastDayColor' => '',
    'permissionScheme' => 'Default',
    'productionMode' => '1',
    'pwdStrength' => 'medium',
    'regionalHolidays' => '0',
    'regionalHolidaysColor' => 'CC0000',
    'repeatHeaderCount' => '0',
    'satBusi' => '0',
    'showAlerts' => 'all',
    'showAvatars' => '1',
    'showMonths' => '1',
    'showRegionButton' => '1',
    'showRemainder' => '0',
    'showRoleIcons' => '1',
    'showSummary' => '1',
    'showTooltipCount' => '0',
    'showTwoMonths' => '0',
    'showUserIcons' => '0',
    'showUserRegion' => '1',
    'showWeekNumbers' => '1',
    'sortByOrderKey' => '1',
    'statsDefaultColorAbsences' => 'red',
    'statsDefaultColorAbsencetype' => 'cyan',
    'statsDefaultColorPresences' => 'green',
    'statsDefaultColorPresencetype' => 'magenta',
    'statsDefaultColorRemainder' => 'orange',
    'statsDefaultColorTrends' => 'red',
    'statsDefaultColorDayofweek' => 'purple',
    'statsDefaultColorDuration' => 'orange',
    'summaryAbsenceTextColor' => 'D9534F',
    'summaryPresenceTextColor' => '5CB85C',
    'sunColor' => '',
    'sunBusi' => '0',
    'supportMobile' => '0',
    'symbolAsIcon' => '0',
    'takeover' => '0',
    'timeZone' => 'Europe/Berlin',
    'todayBorderColor' => 'FFB300',
    'todayBorderSize' => '2',
    'trustedRoles' => '1',
    'underMaintenance' => '0',
    'userCustom1' => 'Custom Field 1',
    'userCustom2' => 'Custom Field 2',
    'userCustom3' => 'Custom Field 3',
    'userCustom4' => 'Custom Field 4',
    'userCustom5' => 'Custom Field 5',
    'userManual' => 'https%3A%2F%2Flewe.gitbook.io%2Fteamcal-neo%2F',
    'userSearch' => '0',
    'usersPerPage' => '0',
    'versionCompare' => '1',
    'welcomeIcon' => 'None',
    'welcomeText' => '<h3><img alt="" src="public/upload/files/logo-128.png" style="float:left; height:128px; margin-bottom:24px; margin-right:24px; width:128px" />Welcome to TeamCal Neo 5</h3>

<p>TeamCal Neo is a day-based online calendar that allows to easily manage your team\'s events and absences and displays them in an intuitive interface. You can manage absence types, holidays, regional calendars and much more.</p>

<p>TeamCal Neo requires a yearly license subscription for a fee.</p>

<p>Its little brother "<a href="http://tcneobasic.lewe.com">TeamCal Neo Basic</a>" , however, remains free and offers the core features of the calendar.</p>

<h3>Links:</h3>

<ul>
  <li><a href="https://teamcalneo.lewe.com/" target="_blank">Product Page</a></li>
  <li><a href="https://lewe.gitbook.io/teamcal-neo/" target="_blank">Documentation</a></li>
</ul>

<h3>Login</h3>

<p>Select Login from the User menu to login and use the following accounts to give this demo a test drive:</p>

<p><strong>Admin account:</strong></p>

<p>admin/Qwer!1234</p>

<p><strong>User accounts:</strong></p>

<p>ccarl/Qwer!1234<br />
blightyear/Qwer!1234<br />
dduck/Qwer!1234<br />
einstein/Qwer!1234<br />
sgonzalez/Qwer!1234<br />
phead/Qwer!1234<br />
mmouse/Qwer!1234<br />
mimouse/Qwer!1234<br />
sman/Qwer!1234</p>

<p><strong>LDAP test account (when activating the <a href="https://lewe.gitbook.io/teamcal-neo/administration/ldap-authentication">LDAP test configuration</a>):</strong></p>

<p>einstein/password</p>
',
    'welcomeTitle' => 'Welcome To TeamCal Neo',
  ),
);
