<?php
// AUTO-GENERATED by tools/generate_db_manifest.php - DO NOT EDIT.
// Source: sql/basic.sql
// Generated: 2026-09-30T19:43:47+00:00
//
// Used by the Database Structure repair feature to diff the live
// database against the schema shipped with this release. Table names
// are stored UNPREFIXED; the repair engine applies the installation's
// db_table_prefix at runtime.

return array (
  'generated' => '2026-09-30T19:43:47+00:00',
  'source' => 'sql/basic.sql',
  'prefix' => 'tcneo_',
  'tables' => 
  array (
    'roles' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'default\'',
        ),
        4 => 
        array (
          'name' => 'created',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp()',
        ),
        5 => 
        array (
          'name' => 'updated',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_name',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 6',
    ),
    'regions' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) NOT NULL DEFAULT \'\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_name',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 2',
    ),
    'region_role' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'region_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'role_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        3 => 
        array (
          'name' => 'access',
          'definition' => 'varchar(4) NOT NULL DEFAULT \'edit\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_region_role',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'region_id',
            1 => 'role_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_rr_region',
          'columns' => 
          array (
            0 => 'region_id',
          ),
          'ref_table' => 'regions',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_rr_role',
          'columns' => 
          array (
            0 => 'role_id',
          ),
          'ref_table' => 'roles',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'holidays' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(6) NOT NULL DEFAULT \'000000\'',
        ),
        4 => 
        array (
          'name' => 'bgcolor',
          'definition' => 'varchar(6) NOT NULL DEFAULT \'ffffff\'',
        ),
        5 => 
        array (
          'name' => 'businessday',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        6 => 
        array (
          'name' => 'noabsence',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        7 => 
        array (
          'name' => 'keepweekendcolor',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        8 => 
        array (
          'name' => 'is_system',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_name',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 6',
    ),
    'absences' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(80) NOT NULL',
        ),
        2 => 
        array (
          'name' => 'symbol',
          'definition' => 'char(1) NOT NULL DEFAULT \'A\'',
        ),
        3 => 
        array (
          'name' => 'icon',
          'definition' => 'varchar(40) NOT NULL',
        ),
        4 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(6) NOT NULL',
        ),
        5 => 
        array (
          'name' => 'bgcolor',
          'definition' => 'varchar(6) NOT NULL',
        ),
        6 => 
        array (
          'name' => 'bgtrans',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        7 => 
        array (
          'name' => 'factor',
          'definition' => 'float NOT NULL',
        ),
        8 => 
        array (
          'name' => 'allowance',
          'definition' => 'float NOT NULL',
        ),
        9 => 
        array (
          'name' => 'allowmonth',
          'definition' => 'float NOT NULL',
        ),
        10 => 
        array (
          'name' => 'allowweek',
          'definition' => 'float NOT NULL',
        ),
        11 => 
        array (
          'name' => 'counts_as',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        12 => 
        array (
          'name' => 'show_in_remainder',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        13 => 
        array (
          'name' => 'show_totals',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        14 => 
        array (
          'name' => 'approval_required',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        15 => 
        array (
          'name' => 'counts_as_present',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        16 => 
        array (
          'name' => 'manager_only',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        17 => 
        array (
          'name' => 'hide_in_profile',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        18 => 
        array (
          'name' => 'confidential',
          'definition' => 'tinyint(1) NOT NULL',
        ),
        19 => 
        array (
          'name' => 'takeover',
          'definition' => 'tinyint(1) NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_counts_as',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'counts_as',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_absences_counts_as',
          'columns' => 
          array (
            0 => 'counts_as',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'groups' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) NOT NULL DEFAULT \'\'',
        ),
        3 => 
        array (
          'name' => 'avatar',
          'definition' => 'varchar(255) NOT NULL DEFAULT \'default_group.png\'',
        ),
        4 => 
        array (
          'name' => 'minpresent',
          'definition' => 'smallint(6) NOT NULL DEFAULT 0',
        ),
        5 => 
        array (
          'name' => 'maxabsent',
          'definition' => 'smallint(6) NOT NULL DEFAULT 9999',
        ),
        6 => 
        array (
          'name' => 'minpresentwe',
          'definition' => 'smallint(6) NOT NULL DEFAULT 0',
        ),
        7 => 
        array (
          'name' => 'maxabsentwe',
          'definition' => 'smallint(6) NOT NULL DEFAULT 9999',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'absence_group' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'absence_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'group_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_absence_group',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'absence_id',
            1 => 'group_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_ag_absence',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_ag_group',
          'columns' => 
          array (
            0 => 'group_id',
          ),
          'ref_table' => 'groups',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'patterns' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'description',
          'definition' => 'varchar(100) NOT NULL DEFAULT \'\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'pattern_days' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'pattern_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'weekday',
          'definition' => 'tinyint(3) unsigned NOT NULL COMMENT \'1=Monday..7=Sunday (ISO-8601)\'',
        ),
        3 => 
        array (
          'name' => 'absence_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_pattern_weekday',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'pattern_id',
            1 => 'weekday',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_pd_pattern',
          'columns' => 
          array (
            0 => 'pattern_id',
          ),
          'ref_table' => 'patterns',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_pd_absence',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'RESTRICT',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
        0 => 
        array (
          'name' => 'chk_pd_weekday',
          'expression' => '`weekday` BETWEEN 1 AND 7',
        ),
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'users' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) NOT NULL',
        ),
        2 => 
        array (
          'name' => 'password',
          'definition' => 'varchar(255) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'firstname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'lastname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'email',
          'definition' => 'varchar(100) DEFAULT NULL',
        ),
        6 => 
        array (
          'name' => 'order_key',
          'definition' => 'varchar(80) NOT NULL DEFAULT \'0\'',
        ),
        7 => 
        array (
          'name' => 'role_id',
          'definition' => 'int(10) unsigned NOT NULL DEFAULT 2',
        ),
        8 => 
        array (
          'name' => 'locked',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        9 => 
        array (
          'name' => 'hidden',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        10 => 
        array (
          'name' => 'onhold',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        11 => 
        array (
          'name' => 'verify',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        12 => 
        array (
          'name' => 'is_system',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        13 => 
        array (
          'name' => 'bad_logins',
          'definition' => 'tinyint(4) NOT NULL DEFAULT 0',
        ),
        14 => 
        array (
          'name' => 'bad_logins_start',
          'definition' => 'int(10) unsigned NOT NULL DEFAULT 0',
        ),
        15 => 
        array (
          'name' => 'grace_start',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        16 => 
        array (
          'name' => 'last_pw_change',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        17 => 
        array (
          'name' => 'last_login',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        18 => 
        array (
          'name' => 'created',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        19 => 
        array (
          'name' => 'updated_at',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
        ),
        20 => 
        array (
          'name' => 'oidc_sub',
          'definition' => 'varchar(255) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_username',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        2 => 
        array (
          'name' => 'uk_oidc_sub',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'oidc_sub',
          ),
        ),
        3 => 
        array (
          'name' => 'idx_lastname_firstname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'lastname',
            1 => 'firstname',
          ),
        ),
        4 => 
        array (
          'name' => 'idx_role_lastname_firstname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'role_id',
            1 => 'lastname',
            2 => 'firstname',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_users_role',
          'columns' => 
          array (
            0 => 'role_id',
          ),
          'ref_table' => 'roles',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'RESTRICT',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'calendar_days' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'region_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'day',
          'definition' => 'date NOT NULL',
        ),
        3 => 
        array (
          'name' => 'holiday_id',
          'definition' => 'int(10) unsigned NOT NULL DEFAULT 1',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_region_day',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'region_id',
            1 => 'day',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_day',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'day',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_cd_region',
          'columns' => 
          array (
            0 => 'region_id',
          ),
          'ref_table' => 'regions',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_cd_holiday',
          'columns' => 
          array (
            0 => 'holiday_id',
          ),
          'ref_table' => 'holidays',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'RESTRICT',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'absence_days' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'day',
          'definition' => 'date NOT NULL',
        ),
        3 => 
        array (
          'name' => 'absence_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        4 => 
        array (
          'name' => 'created_at',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp()',
        ),
        5 => 
        array (
          'name' => 'updated_at',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_user_day',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'day',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_day',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'day',
          ),
        ),
        3 => 
        array (
          'name' => 'idx_absence',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_ad_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_ad_absence',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'RESTRICT',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'allowances' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'absence_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        3 => 
        array (
          'name' => 'carryover',
          'definition' => 'smallint(6) NOT NULL DEFAULT 0',
        ),
        4 => 
        array (
          'name' => 'allowance',
          'definition' => 'smallint(6) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_user_absence',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'absence_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_al_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_al_absence',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'RESTRICT',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'attachments' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'filename',
          'definition' => 'varchar(255) NOT NULL',
        ),
        2 => 
        array (
          'name' => 'uploader_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_filename',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'filename',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_att_uploader',
          'columns' => 
          array (
            0 => 'uploader_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'user_attachment' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'attachment_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_user_attachment',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'attachment_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_ua_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_ua_attachment',
          'columns' => 
          array (
            0 => 'attachment_id',
          ),
          'ref_table' => 'attachments',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'config' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'name',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'value',
          'definition' => 'text NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_name',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'name',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'daynotes' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'day',
          'definition' => 'date NOT NULL',
        ),
        2 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned DEFAULT NULL COMMENT \'NULL = global note (all users), was username = \'\'all\'\' sentinel\'',
        ),
        3 => 
        array (
          'name' => 'region_id',
          'definition' => 'int(10) unsigned DEFAULT NULL COMMENT \'NULL = regionless\'',
        ),
        4 => 
        array (
          'name' => 'daynote',
          'definition' => 'text DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(16) NOT NULL DEFAULT \'default\'',
        ),
        6 => 
        array (
          'name' => 'confidential',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_day_user_region',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'day',
            1 => 'user_id',
            2 => 'region_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_dn_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_dn_region',
          'columns' => 
          array (
            0 => 'region_id',
          ),
          'ref_table' => 'regions',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'log' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'type',
          'definition' => 'varchar(40) DEFAULT NULL',
        ),
        2 => 
        array (
          'name' => 'timestamp',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        3 => 
        array (
          'name' => 'ip',
          'definition' => 'varchar(40) DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'user',
          'definition' => 'varchar(40) DEFAULT NULL COMMENT \'Denormalized username snapshot, no FK - log rows survive user rename/delete\'',
        ),
        5 => 
        array (
          'name' => 'event',
          'definition' => 'text DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_log_timestamp',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'timestamp',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_log_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user',
          ),
        ),
        3 => 
        array (
          'name' => 'idx_log_type',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'type',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'messages' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'timestamp',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        2 => 
        array (
          'name' => 'text',
          'definition' => 'text NOT NULL',
        ),
        3 => 
        array (
          'name' => 'type',
          'definition' => 'varchar(8) NOT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_type',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'type',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'user_message' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'message_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        3 => 
        array (
          'name' => 'popup',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_user_message',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'message_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_um_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_um_message',
          'columns' => 
          array (
            0 => 'message_id',
          ),
          'ref_table' => 'messages',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'permissions' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'scheme',
          'definition' => 'varchar(80) NOT NULL',
        ),
        2 => 
        array (
          'name' => 'permission',
          'definition' => 'varchar(40) NOT NULL',
        ),
        3 => 
        array (
          'name' => 'role_id',
          'definition' => 'int(10) unsigned NOT NULL DEFAULT 1',
        ),
        4 => 
        array (
          'name' => 'allowed',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_scheme_permission_role',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'scheme',
            1 => 'permission',
            2 => 'role_id',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_scheme',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'scheme',
          ),
        ),
        3 => 
        array (
          'name' => 'idx_permission',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'permission',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_perm_role',
          'columns' => 
          array (
            0 => 'role_id',
          ),
          'ref_table' => 'roles',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'user_group' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'group_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        3 => 
        array (
          'name' => 'type',
          'definition' => 'enum(\'member\', \'manager\', \'guest\') NOT NULL DEFAULT \'member\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_user_group',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'group_id',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_group_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'group_id',
            1 => 'user_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_ug_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_ug_group',
          'columns' => 
          array (
            0 => 'group_id',
          ),
          'ref_table' => 'groups',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'user_option' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'option',
          'definition' => 'varchar(40) NOT NULL',
        ),
        3 => 
        array (
          'name' => 'value',
          'definition' => 'text DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'uk_user_option',
          'type' => 'UNIQUE',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'option',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_option',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'option',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_uo_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_users' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        1 => 
        array (
          'name' => 'username',
          'definition' => 'varchar(40) NOT NULL DEFAULT \'\'',
        ),
        2 => 
        array (
          'name' => 'password',
          'definition' => 'varchar(255) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'firstname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'lastname',
          'definition' => 'varchar(80) DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'email',
          'definition' => 'varchar(100) DEFAULT NULL',
        ),
        6 => 
        array (
          'name' => 'order_key',
          'definition' => 'varchar(80) NOT NULL DEFAULT \'0\'',
        ),
        7 => 
        array (
          'name' => 'role_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        8 => 
        array (
          'name' => 'locked',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        9 => 
        array (
          'name' => 'hidden',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        10 => 
        array (
          'name' => 'onhold',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        11 => 
        array (
          'name' => 'verify',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        12 => 
        array (
          'name' => 'is_system',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
        13 => 
        array (
          'name' => 'bad_logins',
          'definition' => 'tinyint(4) NOT NULL DEFAULT 0',
        ),
        14 => 
        array (
          'name' => 'bad_logins_start',
          'definition' => 'int(10) unsigned NOT NULL DEFAULT 0',
        ),
        15 => 
        array (
          'name' => 'grace_start',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        16 => 
        array (
          'name' => 'last_pw_change',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        17 => 
        array (
          'name' => 'last_login',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        18 => 
        array (
          'name' => 'created',
          'definition' => 'datetime NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
        ),
        19 => 
        array (
          'name' => 'updated_at',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
        ),
        20 => 
        array (
          'name' => 'oidc_sub',
          'definition' => 'varchar(255) DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_username',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'username',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_firstname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'firstname',
          ),
        ),
        3 => 
        array (
          'name' => 'idx_lastname',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'lastname',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_ausers_role',
          'columns' => 
          array (
            0 => 'role_id',
          ),
          'ref_table' => 'roles',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_absence_days' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'bigint(20) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'day',
          'definition' => 'date NOT NULL',
        ),
        3 => 
        array (
          'name' => 'absence_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'created_at',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp()',
        ),
        5 => 
        array (
          'name' => 'updated_at',
          'definition' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user_day',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
            1 => 'day',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_aad_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_aad_absence',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_allowances' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'absence_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'carryover',
          'definition' => 'smallint(6) DEFAULT 0',
        ),
        4 => 
        array (
          'name' => 'allowance',
          'definition' => 'smallint(6) DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_aal_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_aal_absence',
          'columns' => 
          array (
            0 => 'absence_id',
          ),
          'ref_table' => 'absences',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_daynotes' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'day',
          'definition' => 'date NOT NULL',
        ),
        2 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'region_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        4 => 
        array (
          'name' => 'daynote',
          'definition' => 'text DEFAULT NULL',
        ),
        5 => 
        array (
          'name' => 'color',
          'definition' => 'varchar(16) NOT NULL DEFAULT \'default\'',
        ),
        6 => 
        array (
          'name' => 'confidential',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_adn_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_adn_region',
          'columns' => 
          array (
            0 => 'region_id',
          ),
          'ref_table' => 'regions',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_user_attachment' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'attachment_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_aua_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_aua_attachment',
          'columns' => 
          array (
            0 => 'attachment_id',
          ),
          'ref_table' => 'attachments',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_user_group' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'group_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'type',
          'definition' => 'enum(\'member\', \'manager\', \'guest\') NOT NULL DEFAULT \'member\'',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_aug_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_aug_group',
          'columns' => 
          array (
            0 => 'group_id',
          ),
          'ref_table' => 'groups',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_user_message' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'message_id',
          'definition' => 'int(10) unsigned DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'popup',
          'definition' => 'tinyint(1) NOT NULL DEFAULT 0',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_aum_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
        1 => 
        array (
          'name' => 'fk_aum_message',
          'columns' => 
          array (
            0 => 'message_id',
          ),
          'ref_table' => 'messages',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'SET NULL',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
    'archive_user_option' => 
    array (
      'columns' => 
      array (
        0 => 
        array (
          'name' => 'id',
          'definition' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
        ),
        1 => 
        array (
          'name' => 'user_id',
          'definition' => 'int(10) unsigned NOT NULL',
        ),
        2 => 
        array (
          'name' => 'option',
          'definition' => 'varchar(40) DEFAULT NULL',
        ),
        3 => 
        array (
          'name' => 'value',
          'definition' => 'text DEFAULT NULL',
        ),
      ),
      'indexes' => 
      array (
        0 => 
        array (
          'name' => 'PRIMARY',
          'type' => 'PRIMARY',
          'columns' => 
          array (
            0 => 'id',
          ),
        ),
        1 => 
        array (
          'name' => 'idx_user',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'user_id',
          ),
        ),
        2 => 
        array (
          'name' => 'idx_option',
          'type' => 'INDEX',
          'columns' => 
          array (
            0 => 'option',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        0 => 
        array (
          'name' => 'fk_auo_user',
          'columns' => 
          array (
            0 => 'user_id',
          ),
          'ref_table' => 'archive_users',
          'ref_columns' => 
          array (
            0 => 'id',
          ),
          'on_delete' => 'CASCADE',
          'on_update' => '',
        ),
      ),
      'checks' => 
      array (
      ),
      'engine' => 'InnoDB',
      'options' => 'ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci',
    ),
  ),
  'config' => 
  array (
    'activateMessages' => '1',
    'adminApproval' => '1',
    'alertAutocloseDanger' => '0',
    'alertAutocloseDelay' => '3000',
    'alertAutocloseSuccess' => '1',
    'alertAutocloseWarning' => '0',
    'allowRegistration' => '1',
    'appDescription' => 'A day based online calendar to manage team events',
    'appKeywords' => 'lewe teamcal neo calendar absence event team',
    'appTitle' => 'TeamCal Neo',
    'appURL' => '#',
    'avatarHeight' => '0',
    'avatarMaxSize' => '0',
    'avatarWidth' => '0',
    'badLogins' => '5',
    'calendarFontSize' => '100',
    'cookieConsent' => '1',
    'cookieLifetime' => '80000',
    'currYearRoles' => '3,2',
    'currentYearOnly' => '0',
    'dbURL' => '#',
    'debugHide' => '0',
    'declAbsence' => '0',
    'declAbsenceEnddate' => '',
    'declAbsencePeriod' => 'nowForever',
    'declAbsenceStartdate' => '',
    'declApplyToAll' => '0',
    'declBase' => 'group',
    'declBefore' => '0',
    'declBeforeDate' => '2026-01-01',
    'declBeforeEnddate' => '',
    'declBeforeOption' => 'date',
    'declBeforePeriod' => 'nowForever',
    'declBeforeStartdate' => '',
    'declNotifyAdmin' => '0',
    'declNotifyDirector' => '0',
    'declNotifyManager' => '1',
    'declNotifyUser' => '1',
    'declPeriod1' => '0',
    'declPeriod1End' => '',
    'declPeriod1Enddate' => '',
    'declPeriod1Message' => '',
    'declPeriod1Period' => '',
    'declPeriod1Start' => '',
    'declPeriod1Startdate' => '',
    'declPeriod2' => '0',
    'declPeriod2End' => '',
    'declPeriod2Enddate' => '',
    'declPeriod2Message' => '',
    'declPeriod2Period' => '',
    'declPeriod2Start' => '',
    'declPeriod2Startdate' => '',
    'declPeriod3' => '0',
    'declPeriod3End' => '',
    'declPeriod3Enddate' => '',
    'declPeriod3Message' => '',
    'declPeriod3Period' => '',
    'declPeriod3Start' => '',
    'declPeriod3Startdate' => '',
    'declScope' => '2',
    'declThreshold' => '40',
    'defaultHomepage' => 'home',
    'defaultLanguage' => 'english',
    'defaultMenu' => 'sidebar',
    'defgroupfilter' => 'all',
    'defregion' => 'Default',
    'disableTfa' => '0',
    'emailConfirmation' => '1',
    'emailNoPastNotifications' => '0',
    'emailNotifications' => '0',
    'firstDayOfWeek' => '1',
    'font' => 'default',
    'footerCopyright' => 'Lewe.com',
    'footerCopyrightUrl' => 'https://www.lewe.com',
    'footerSocialLinks' => 'https://www.linkedin.com/in/george-lewe-a9ab6411b',
    'forceTfa' => '0',
    'gdprController' => 'ACME Inc.
123 Street
Hometown, XY 4567
Germany
Email: info@acme.com',
    'gdprFacebook' => '0',
    'gdprGoogleAnalytics' => '0',
    'gdprGooglePlus' => '0',
    'gdprInstagram' => '0',
    'gdprLinkedin' => '1',
    'gdprOfficer' => 'John Doe
Phone: +49 555 12345
Email: john.doe@acme.com',
    'gdprOrganization' => 'ACME Inc.',
    'gdprPaypal' => '0',
    'gdprPinterest' => '0',
    'gdprPolicyPage' => '1',
    'gdprSlideshare' => '0',
    'gdprTumblr' => '0',
    'gdprTwitter' => '0',
    'gdprXing' => '1',
    'gdprYoutube' => '0',
    'googleAnalytics' => '0',
    'googleAnalyticsID' => '',
    'gracePeriod' => '300',
    'hideDaynotes' => '0',
    'hideManagerOnlyAbsences' => '0',
    'hideManagers' => '0',
    'homepage' => 'home',
    'includeRemainder' => '0',
    'includeRemainderTotal' => '0',
    'includeSummary' => '0',
    'includeTotals' => '0',
    'jqtheme' => 'base',
    'licExpiryWarning' => '30',
    'licKey' => '',
    'logCalendar' => '1',
    'logCalendarOptions' => '1',
    'logConfig' => '1',
    'logDatabase' => '1',
    'logDaynote' => '0',
    'logGroup' => '1',
    'logImport' => '1',
    'logLanguage' => 'english',
    'logLog' => '1',
    'logLogin' => '1',
    'logMessage' => '0',
    'logMonth' => '0',
    'logNews' => '1',
    'logPattern' => '1',
    'logPermission' => '1',
    'logRegion' => '1',
    'logRegistration' => '1',
    'logRole' => '1',
    'logUpload' => '1',
    'logUser' => '1',
    'logcolorCalendar' => 'default',
    'logcolorCalendarOptions' => 'danger',
    'logcolorConfig' => 'danger',
    'logcolorDatabase' => 'warning',
    'logcolorDaynote' => 'default',
    'logcolorGroup' => 'primary',
    'logcolorImport' => 'warning',
    'logcolorLog' => 'default',
    'logcolorLogin' => 'success',
    'logcolorMessage' => 'primary',
    'logcolorMonth' => 'default',
    'logcolorPattern' => 'success',
    'logcolorPermission' => 'warning',
    'logcolorRegion' => 'success',
    'logcolorRegistration' => 'success',
    'logcolorRole' => 'primary',
    'logcolorUpload' => 'primary',
    'logcolorUser' => 'primary',
    'logfilterCalendar Options' => '0',
    'logfilterCalendar' => '1',
    'logfilterCalendarOptions' => '1',
    'logfilterConfig' => '1',
    'logfilterDatabase' => '1',
    'logfilterDaynote' => '0',
    'logfilterGroup' => '1',
    'logfilterImport' => '1',
    'logfilterLog' => '1',
    'logfilterLogin' => '1',
    'logfilterMessage' => '0',
    'logfilterMonth' => '0',
    'logfilterNews' => '1',
    'logfilterPattern' => '1',
    'logfilterPermission' => '1',
    'logfilterRegion' => '1',
    'logfilterRegistration' => '1',
    'logfilterRole' => '1',
    'logfilterUpload' => '1',
    'logfilterUser' => '1',
    'logfrom' => '2026-01-01 00:00:00.000000',
    'logperiod' => 'curr_all',
    'logto' => '2026-12-31 23:59:59.999999',
    'mailFrom' => 'TeamCal Neo',
    'mailReply' => 'webmaster@mysite.com',
    'mailSMTP' => '0',
    'mailSMTPAnonymous' => '0',
    'mailSMTPSSL' => '0',
    'mailSMTPhost' => '',
    'mailSMTPpassword' => '',
    'mailSMTPport' => '0',
    'mailSMTPusername' => '',
    'managerOnlyIncludesAdministrator' => '0',
    'markConfidential' => '0',
    'matomoAnalytics' => '0',
    'matomoSiteId' => '',
    'matomoUrl' => '',
    'monitorAbsence' => '0',
    'noCaching' => '1',
    'noIndex' => '0',
    'notificationsAllGroups' => '0',
    'pageHelp' => '1',
    'pastDayColor' => '',
    'permissionScheme' => 'Default',
    'productionMode' => '1',
    'pwdStrength' => 'medium',
    'regionalHolidays' => '0',
    'regionalHolidaysColor' => 'CC0000',
    'repeatHeaderCount' => '0',
    'satBusi' => '0',
    'showAlerts' => 'all',
    'showAvatars' => '1',
    'showMonths' => '1',
    'showRegionButton' => '1',
    'showRemainder' => '0',
    'showRoleIcons' => '1',
    'showSummary' => '1',
    'showTooltipCount' => '0',
    'showTwoMonths' => '0',
    'showUserIcons' => '0',
    'showUserRegion' => '1',
    'showWeekNumbers' => '1',
    'sortByOrderKey' => '1',
    'statsDefaultColorAbsences' => 'red',
    'statsDefaultColorAbsencetype' => 'cyan',
    'statsDefaultColorPresences' => 'green',
    'statsDefaultColorPresencetype' => 'magenta',
    'statsDefaultColorRemainder' => 'orange',
    'statsDefaultColorTrends' => 'red',
    'statsDefaultColorDayofweek' => 'purple',
    'statsDefaultColorDuration' => 'orange',
    'summaryAbsenceTextColor' => 'D9534F',
    'summaryPresenceTextColor' => '5CB85C',
    'sunColor' => '',
    'sunBusi' => '0',
    'supportMobile' => '0',
    'symbolAsIcon' => '0',
    'takeover' => '0',
    'timeZone' => 'Europe/Berlin',
    'todayBorderColor' => 'FFB300',
    'todayBorderSize' => '2',
    'trustedRoles' => '1',
    'underMaintenance' => '0',
    'userCustom1' => 'Custom Field 1',
    'userCustom2' => 'Custom Field 2',
    'userCustom3' => 'Custom Field 3',
    'userCustom4' => 'Custom Field 4',
    'userCustom5' => 'Custom Field 5',
    'userManual' => 'https%3A%2F%2Flewe.gitbook.io%2Fteamcal-neo%2F',
    'userSearch' => '0',
    'usersPerPage' => '0',
    'versionCompare' => '1',
    'welcomeIcon' => 'None',
    'welcomeText' => '<h3><img alt="" src="public/upload/files/logo-128.png" style="float:left; height:128px; margin-bottom:24px; margin-right:24px; width:128px" />Welcome to TeamCal Neo 5</h3>

<p>TeamCal Neo is a day-based online calendar that allows to easily manage your team\'s events and absences and displays them in an intuitive interface. You can manage absence types, holidays, regional calendars and much more.</p>

<p>TeamCal Neo requires a yearly license subscription for a fee.</p>

<p>Its little brother "<a href="http://tcneobasic.lewe.com">TeamCal Neo Basic</a>" , however, remains free and offers the core features of the calendar.</p>

<h3>Links:</h3>

<ul>
  <li><a href="https://teamcalneo.lewe.com/" target="_blank">Product Page</a></li>
  <li><a href="https://lewe.gitbook.io/teamcal-neo/" target="_blank">Documentation</a></li>
</ul>

<h3>Login</h3>

<p>Select Login from the User menu to login and use the following accounts to give this demo a test drive:</p>

<p><strong>Admin account:</strong></p>

<p>admin/Qwer!1234</p>

<p><strong>User accounts:</strong></p>

<p>ccarl/Qwer!1234<br />
blightyear/Qwer!1234<br />
dduck/Qwer!1234<br />
einstein/Qwer!1234<br />
sgonzalez/Qwer!1234<br />
phead/Qwer!1234<br />
mmouse/Qwer!1234<br />
mimouse/Qwer!1234<br />
sman/Qwer!1234</p>

<p><strong>LDAP test account (when activating the <a href="https://lewe.gitbook.io/teamcal-neo/administration/ldap-authentication">LDAP test configuration</a>):</strong></p>

<p>einstein/password</p>
',
    'welcomeTitle' => 'Welcome To TeamCal Neo',
  ),
);
