name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: '8.2'
          extensions: ctype, pdo, zip
          coverage: none

      - name: Install Production Dependencies
        run: composer install --no-dev --prefer-dist --no-progress --optimize-autoloader

      - name: Create ZIP Archive
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          IFS='.' read -r VMAJOR VMINOR VPATCH <<< "$VERSION"
          ZIP_NAME="tcneo_$(printf '%02d' $VMAJOR)$(printf '%02d' $VMINOR)$(printf '%02d' $VPATCH).zip"
          zip -r "$ZIP_NAME" . -x ".git/*" -x "RELEASE_NOTES.md" -x "*.zip"

      - name: Create Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
          body_path: RELEASE_NOTES.md
          generate_release_notes: true
